### ISSUE TITLE
Cannot start Game in solution branch as exception was thrown out

### ISSUE THREAD

**Issue by ny83427** [ny83427/java-tutorial#1]
When I switch to branch of `solution` and run `Game.java` in chapter4, it failed with exception like this:

```java
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init>
  at com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)
  at com.sun.glass.ui.Screen.initScreens(Screen.java:412)
  at com.sun.glass.ui.Application.lambda$run$1(Application.java:152)
  at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
  at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
  at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ny83427** [comment]
This issue was possibly an environment issue and the easiest solution in [Stackoverflow ](https://stackoverflow.com/questions/52906570/javafx-11-using-maven-throws-exception-windowsnativerunloopthread)would be adding vm options like this before run `Game.java`:

```java
-Djava.library.path=C:/
```

If you have installed both jdk8 and jdk11, and jdk8 was in path, even if you have set your project SDK to jdk11, this issue would also happen. Another approach can be simply add jdk11\bin to path, as jdk8 compiler level is compatible with jdk11.
